"""Ashby board harvester.

Turns companies the scan has ALREADY seen into standing, keyless sources on
the one ATS whose portal adapter completes end-to-end.

Why Ashby first: it is the only confirmed full-auto adapter (greenhouse and
lever wall at a captcha), so supply landed there is the supply that can
actually become an autonomous submission.

Measured 2026-09-16 against the live board API: of the 98 companies that had
ever scored >= 6, twenty-three have a live Ashby board, carrying 1,238 open
roles between them -- against the five ashby slugs sources.yaml configures.
"""
from __future__ import annotations

import re
from pathlib import Path

import yaml

from cv_tailor.job_sources import fetch_ashby_org

_GENERATED_HEADER = (
    "# GENERATED by cv_tailor.harvest -- do not hand-edit.\n"
    "#\n"
    "# Ashby boards discovered from companies the scan has already seen, and\n"
    "# validated against the keyless board API (jobs > 0, never HTTP status).\n"
    "# Harvested slugs auto-enrol: there is no review queue.\n"
    "#\n"
    "# To drop a board permanently use harvest.disable_ashby_slug() (or the\n"
    "# scripts/harvest.py --disable flag): deleting it from `sources` here is\n"
    "# NOT enough, because the next harvest would simply find and re-add it.\n"
    "# A slug listed under `disabled` is dropped from the scan and can never\n"
    "# be re-enrolled.\n"
    "#\n"
    "# sources.yaml is the hand-curated list and is deliberately untouched by\n"
    "# this file: a machine rewrite there would destroy its measured notes.\n"
)

# Aggregators wearing an employer's clothes. An aggregator board is not an
# employer board: enrolling one pours thousands of aggregator-quality
# postings into a scan that sees ~11 new postings a day, burning scoring
# spend on jobs that never clear the floor -- the same failure mode as the
# arbeitnow.com/JOB_BOARD_DOMAINS bug. The board API cannot tell us which is
# which, so this list is the only guard, and it is matched on the DERIVED
# SLUG so a company's display spelling cannot slip past it.
DENIED_SLUGS = frozenset({
    "jobgether", "jobright", "remoterocketship", "wellfound", "otta",
    "welcometothejungle", "hired", "ziprecruiter", "indeed", "linkedin",
})


def validate_ashby_slug(slug: str) -> bool:
    """True iff `slug` names a board that currently has open roles.

    Validity is len(jobs) > 0, NEVER the HTTP status: a slug with no board at
    all answers HTTP 200 with jobs: [] (verified live on 'vercel'), so reading
    the status would enrol every typo as a source.

    Fails closed on any probe failure -- a timeout says nothing about whether
    the board exists, and an unreachable probe must never enrol a source.
    """
    if not slug:
        return False
    try:
        return len(fetch_ashby_org(slug)) > 0
    except Exception:       # noqa: BLE001 -- unknown slugs 404, networks flake
        return False


def _slug_candidates(company: str) -> list[str]:
    """Board-slug guesses derived ONLY from the company name, in the two
    shapes Ashby orgs actually use: squashed ("roompricegenie") and
    hyphenated ("lemon-io"). Both were observed live on 2026-09-16."""
    low = (company or "").lower()
    squashed = re.sub(r"[^a-z0-9]+", "", low)
    hyphenated = re.sub(r"[^a-z0-9]+", "-", low).strip("-")
    return [s for s in dict.fromkeys([squashed, hyphenated]) if s]


def harvest_ashby_slugs(companies, known_slugs=()) -> list[str]:
    """Validated, newly-found Ashby slugs for `companies`, in first-seen order.

    Skips, WITHOUT probing: slugs already configured (enrolment must be
    idempotent -- a slug enrolling twice, or silently replacing an existing
    entry, has to be impossible), denied aggregator slugs, and any slug
    already probed this pass. The pool is every company the scan has ever
    seen, so a duplicate probe is a duplicate request against someone else's
    API for an answer we already have.

    Stops at the first candidate shape that validates: one board per company.
    """
    known = {str(s).strip().lower() for s in (known_slugs or ())}
    found: list[str] = []
    probed: set[str] = set()
    for name in companies or ():
        for slug in _slug_candidates(name):
            if slug in probed or slug in known or slug in DENIED_SLUGS:
                continue
            probed.add(slug)
            if validate_ashby_slug(slug):
                found.append(slug)
                break
    return found


def _read_registry(path) -> dict:
    """The generated registry, or an empty one. A missing file is NOT an
    error: the scan must run normally on a machine that has never
    harvested."""
    p = Path(path)
    if not p.exists():
        return {"sources": [], "disabled": [], "probed": []}
    doc = yaml.safe_load(p.read_text()) or {}
    if not isinstance(doc, dict):
        return {"sources": [], "disabled": [], "probed": []}
    doc.setdefault("sources", [])
    doc.setdefault("disabled", [])
    doc.setdefault("probed", [])
    return doc


def _write_registry(path, doc: dict) -> None:
    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(_GENERATED_HEADER + yaml.safe_dump(doc, sort_keys=False))


def _lower_set(values) -> set[str]:
    return {str(v).strip().lower() for v in (values or []) if str(v).strip()}


def load_harvested_sources(path) -> list[dict]:
    """Harvested source entries in the shape fetch_all consumes, with every
    disabled slug filtered out."""
    doc = _read_registry(path)
    disabled = _lower_set(doc.get("disabled"))
    return [e for e in (doc.get("sources") or [])
            if isinstance(e, dict) and str(e.get("slug", "")).strip().lower() not in disabled]


def enrol_ashby_slugs(path, slugs) -> list[str]:
    """Add `slugs` to the registry, returning the ones actually added.

    Idempotent by construction: a slug already enrolled, or previously
    disabled, is skipped rather than appended or silently replaced.
    """
    doc = _read_registry(path)
    existing = _lower_set(e.get("slug") for e in (doc.get("sources") or []) if isinstance(e, dict))
    disabled = _lower_set(doc.get("disabled"))
    added: list[str] = []
    for raw in slugs or ():
        slug = str(raw).strip()
        low = slug.lower()
        if not slug or low in existing or low in disabled:
            continue
        doc["sources"].append({"kind": "ashby", "slug": slug, "name": slug})
        existing.add(low)
        added.append(slug)
    if added:
        _write_registry(path, doc)
    return added


# 200 probes is roughly a minute of polite sequential requests, and the
# backlog drains over a few mornings rather than in one burst.
DEFAULT_PROBE_LIMIT = 200


def harvest_and_enrol(path, companies, known_slugs=(), limit=DEFAULT_PROBE_LIMIT) -> list[str]:
    """One harvest pass: probe unseen candidate slugs, enrol the boards that
    validate, and remember every slug probed. Returns the slugs added.

    Two properties make this safe to run every morning against someone
    else's API:

    * Probe memory. The pool is every company the scan has ever seen (1,435
      today) and this runs daily, so without a record of what has already
      been asked, each run would repeat thousands of questions it knows the
      answer to. A MISS is recorded too -- "this company has no Ashby board"
      is the common case and the answer most worth keeping.
    * A per-run cap. Day one faces the whole backlog; the cap keeps one
      morning bounded, and the probe memory means the backlog still drains
      across subsequent runs instead of being retried forever.
    """
    doc = _read_registry(path)
    enrolled = _lower_set(e.get("slug") for e in (doc.get("sources") or [])
                          if isinstance(e, dict))
    skip = _lower_set(known_slugs) | enrolled | _lower_set(doc.get("disabled"))
    probed = _lower_set(doc.get("probed"))
    budget = max(0, int(limit))
    added: list[str] = []
    changed = False

    for name in companies or ():
        if budget <= 0:
            break
        for slug in _slug_candidates(name):
            if budget <= 0:
                break
            low = slug.lower()
            if low in skip or low in probed:
                continue
            budget -= 1
            probed.add(low)
            doc["probed"].append(slug)
            changed = True
            if validate_ashby_slug(slug):
                doc["sources"].append({"kind": "ashby", "slug": slug, "name": slug})
                skip.add(low)
                added.append(slug)
                break

    if changed:
        _write_registry(path, doc)
    return added


def disable_ashby_slug(path, slug: str) -> None:
    """Drop a board from the scan permanently. Removing the entry alone would
    not hold -- the next harvest would find the same board and re-add it --
    so the slug is also recorded under `disabled`, which enrolment honours."""
    doc = _read_registry(path)
    low = str(slug).strip().lower()
    doc["sources"] = [e for e in (doc.get("sources") or [])
                      if not (isinstance(e, dict) and str(e.get("slug", "")).strip().lower() == low)]
    if low and low not in _lower_set(doc.get("disabled")):
        doc["disabled"].append(str(slug).strip())
    _write_registry(path, doc)
